---
title: "Tsc2 Report"
output:
  html_notebook:
    code_folding: hide
    toc: yes
  html_document:
    toc: yes
    df_print: paged
editor_options:
  chunk_output_type: inline
---
```{r Data import & prep, include=FALSE}
source("~/GitHub/Tsc2_Analysis/Rxn & TH analysis.R")

partial.data = c("TP 1", "TP 3", "TP 5", "RP 4", "GP 5", "GP 6")
```

# Stats
```{r Stats}
writeLines(paste("Analysis run on", Sys.Date(), "
           Data last loaded on", head(sort(df$Date, decreasing = TRUE), 1), "adding", file_count, "new files.
           There were", nrow(Missing_files), "missing files."))
```

# Thresholds
```{r}
TH.aov = aov(TH ~ Genotype * Duration * `Dur (ms)` + Error(ID), data = TH)
summary(TH.aov)

TH_view %>%
  filter(Duration == "Alone") %>%
  ungroup %>%
  select(-Duration) %>%
  group_by(Genotype) %>%
  summarise(n = n(), 
            `50ms` = mean(na.omit(`50`)) %>% round(digits = 1), 
            `100ms` = mean(na.omit(`100`)) %>% round(digits = 1), 
            `300ms` = mean(na.omit(`300`)) %>% round(digits = 1))
# 
# TH_view %>%
#   group_by(ID) %>%
#   filter(n() > 1)

  
```

# Model

Modeling Type:

```{r Normality, echo=FALSE}
Rxn.aov = aov(LambertW::Gaussianize(Rxn_overall_by_Duration %>%
                    filter(!(ID %in% partial.data)) %>%
                      .$Rxn) ~ Intensity * Genotype * Duration * `Dur (ms)`, 
              data = Rxn_overall_by_Duration %>%
                     filter(!(ID %in% partial.data)))

is_parametric = shapiro.test(Rxn.aov$residuals)$p.value > 0.05

if (is_parametric == TRUE) {writeLines("Normal data proced with ANOVA")} else 
{writeLines(paste("Non-parametric data so use Kruskal followed by Dunn testing. \nShapiro Test: p =", shapiro.test(Rxn.aov$residuals)$p.value %>% round(digits = 3)))}
```

Full Model: <br>
<center> Average Reaction time ~ Intensity * Genotype * Duration (Alone/Mixed) * Duration (ms) </center>
```{r Model, echo=TRUE}
summary(Rxn.aov)
```
# Post Hoc Testing
### Single vs. Mixed Duration
```{r Duration Effect, fig.height = 9.5, fig.width = 8}
Rotation.before = c("GP 1", "GP 2", "GP 3", "TP 2")
Rotation.after = c("RP 3", "RP 5", "RP 6")

kruskal.test(Rxn ~ `Dur (ms)`, 
             data = Rxn_overall_by_Duration %>% 
                    filter(Duration == "Alone"))

postHoc <- 
  FSA::dunnTest(Rxn ~ interaction(Duration, `Dur (ms)`),
           data = Rxn_overall_by_Duration,
           method = "bonf")

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           Alone = str_split_fixed(.$Comparison, ' - ', 2)[,1],
           Mixed = str_split_fixed(.$Comparison, ' - ', 2)[,2]) %>%
    filter(Alone %in% c("Alone.300", "Alone.100", "Alone.50") & Mixed %in% c("Mix.300", "Mix.100", "Mix.50", "Rotating.300", "Rotating.100", "Rotating.50")) %>%
    mutate(Alone = str_extract(Alone, "[:digit:]+") %>% as.numeric(),
           Mixed = str_extract(Mixed, "[:digit:]+") %>% as.numeric(),
           vs = str_extract(Comparison, "- [:alpha:]+") %>% str_remove("- "),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(Alone == Mixed) %>%
    select(Alone, vs, Z, P.adj, Sig) %>%
    arrange(Alone, vs)

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           Mixed = str_split_fixed(.$Comparison, ' - ', 2)[,1],
           Rotating = str_split_fixed(.$Comparison, ' - ', 2)[,2]) %>% 
    filter(Mixed %in% c("Mix.300", "Mix.100", "Mix.50") & Rotating %in% c("Rotating.300", "Rotating.100", "Rotating.50")) %>%
    mutate(Mixed = str_extract(Mixed, "[:digit:]+") %>% as.numeric(),
           Rotating = str_extract(Rotating, "[:digit:]+") %>% as.numeric(),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(Mixed == Rotating) %>%
    select(Mixed, Rotating, Z, P.adj, Sig) %>%
    arrange(Mixed)


Rxn_overall_by_Duration %>%
  filter(!(Intensity %in% c("90"))) %>%
  # filter(ID %in% Rotation.after) %>%
  mutate(Genotype = str_extract(Genotype, "Het|WT")) %>%
  ggplot(aes(x = Intensity, y = Rxn)) +
  # geom_point(aes(group = ID, color = Genotype), alpha = 0.3)+
  # geom_line(aes(group = ID, color = Genotype), alpha = 0.3)+
  stat_summary(aes(linetype = Duration, group = Duration),
               fun = mean,
               fun.min = function(x) mean(x) - se(x),
               fun.max = function(x) mean(x) + se(x),
               geom = "errorbar", width = 1, position = position_dodge(0.1)) +
  stat_summary(aes(shape = Duration, group = Duration),
               fun = mean,
               geom = "point", position = position_dodge(0.1), size = 3) +
  stat_summary(aes(linetype = Duration, group = Duration), fun = mean, geom = "line") +
  labs(title = "Tsc2 Eker",
       caption = paste("Date:", head(sort(df$Date, decreasing = TRUE))),
       x = "Intensity (dB)",
       y = "Reaction time (ms, mean +/- SE)") +
  scale_x_continuous(breaks = seq(20, 80, by = 10)) +
  facet_wrap(~ `Dur (ms)` , ncol = 1) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = rgb(235, 235, 235, 255, maxColorValue = 255))
  )

```

### Genotype
```{r Genotype Effect, fig.height = 9.5, fig.width = 8}
kruskal.test(Rxn ~ Genotype, 
             data = Rxn_overall_by_Duration %>% 
                    filter(Duration == "Alone") %>%
                    filter(!(ID %in% partial.data)))

postHoc <- 
  FSA::dunnTest(Rxn ~ interaction(Genotype, Duration, `Dur (ms)`),
           data = Rxn_overall_by_Duration %>% filter(!(ID %in% partial.data)),
           method = "bonf")

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           G1 = str_extract(.$Comparison, '_[:alpha:]+?\\.') %>% str_remove("_") %>% str_remove("\\."),
           G2 = str_extract(.$Comparison, ' - Tsc2_LE_.*?[:punct:]') %>% str_remove(" - Tsc2_LE_") %>% str_remove("\\."),
           Duration_1 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+? - ') %>% str_remove("\\.[:digit:]+ - "),
           Duration_2 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+?$') %>% str_remove("\\.[:digit:]+"),
           Dur1 = str_extract(.$Comparison, '\\.[:digit:]+? - ') %>% str_remove("\\.") %>% str_remove(" - ") %>% as.numeric(),
           Dur2 = str_extract(.$Comparison, '\\.[:digit:]+?$') %>% str_remove("\\.") %>% as.numeric(),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(Dur1 == Dur2, Duration_1 == Duration_2) %>%
    rename(Stim_Time = Dur1) %>%
    select(G1, G2, Stim_Time, Duration_1, Duration_2, Z, P.adj, Sig) %>%
    arrange(Stim_Time, Duration_1, Duration_2) %>%
    filter(Duration_1 == "Alone")

Rxn_overall_by_Duration %>%
  filter(!(Intensity %in% c("90"))) %>%
  filter(Duration == "Alone") %>%
  filter(!(ID %in% partial.data)) %>%
  mutate(Genotype = str_extract(Genotype, "Het|WT")) %>%
  ggplot(aes(x = Intensity, y = Rxn)) +
  stat_summary(aes(color = Genotype, group = Genotype),
               fun = mean,
               fun.min = function(x) mean(x) - se(x),
               fun.max = function(x) mean(x) + se(x),
               geom = "errorbar", width = 1, position = position_dodge(0.1)) +
  stat_summary(aes(color = Genotype, group = Genotype),
               fun = mean,
               geom = "point", position = position_dodge(0.1), size = 3) +
  stat_summary(aes(color = Genotype, group = Genotype), fun = mean, geom = "line") +
  scale_color_manual(labels = c("WT" = "Wildtype", "Het" = bquote("Tsc2"^"+/-")),
                   values = c("WT" = "black", "Het" = "deepskyblue")) +
  labs(title = "Tsc2 Eker (Single duration)",
       caption = paste("Date:", head(sort(df$Date, decreasing = TRUE))),
       x = "Intensity (dB)",
       y = "Reaction time (ms, mean +/- SE)") +
  scale_x_continuous(breaks = seq(20, 80, by = 10)) +
  facet_wrap( ~ `Dur (ms)`, ncol = 1) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = rgb(235, 235, 235, 255, maxColorValue = 255)),
    legend.position = c(0.87, 0.2),
    legend.key = element_blank()
  )

Rxn_overall_by_Duration %>%
  filter(!(Intensity %in% c("90"))) %>%
  filter(Duration == "Mix") %>%
  filter(!(ID %in% partial.data)) %>%
  mutate(Genotype = str_extract(Genotype, "Het|WT")) %>%
  ggplot(aes(x = Intensity, y = Rxn)) +
  stat_summary(aes(color = Genotype, group = Genotype),
               fun = mean,
               fun.min = function(x) mean(x) - se(x),
               fun.max = function(x) mean(x) + se(x),
               geom = "errorbar", width = 1, position = position_dodge(0.1)) +
  stat_summary(aes(color = Genotype, group = Genotype),
               fun = mean,
               geom = "point", position = position_dodge(0.1), size = 3) +
  stat_summary(aes(color = Genotype, group = Genotype), fun = mean, geom = "line") +
  scale_color_manual(labels = c("WT" = "Wildtype", "Het" = bquote("Tsc2"^"+/-")),
                     values = c("WT" = "black", "Het" = "deepskyblue")) +
  labs(title = "Tsc2 Eker (Mix duration)",
       caption = paste("Date:", head(sort(df$Date, decreasing = TRUE))),
       x = "Intensity (dB)",
       y = "Reaction time (ms, mean +/- SE)") +
  scale_x_continuous(breaks = seq(20, 80, by = 10)) +
  facet_wrap( ~ `Dur (ms)`, ncol = 1) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = rgb(235, 235, 235, 255, maxColorValue = 255)),
    legend.position = c(0.87, 0.2),
    legend.key = element_blank()
  )
```

### Genotype & Duration

```{r Combined, fig.height = 9.5, fig.width = 8}
# kruskal.test(Rxn ~ interaction(Intensity, Duration, `Dur (ms)`), data = Rxn_overall_by_Duration)
# 
# 
postHoc <- 
  FSA::dunnTest(Rxn ~ interaction(Genotype, Duration, `Dur (ms)`),
           data = Rxn_overall_by_Duration %>%
                    filter(!(ID %in% partial.data)) %>%
                    mutate(Duration = gsub("Rotating", "Mix", Duration)),
           method = "bonf")

# print(postHoc, dunn.test.results = TRUE)

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           G1 = str_extract(.$Comparison, '_[:alpha:]+?\\.') %>% str_remove("_") %>% str_remove("\\."),
           G2 = str_extract(.$Comparison, ' - Tsc2_LE_.*?[:punct:]') %>% str_remove(" - Tsc2_LE_") %>% str_remove("\\."),
           Duration_1 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+? - ') %>% str_remove("\\.[:digit:]+ - "),
           Duration_2 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+?$') %>% str_remove("\\.[:digit:]+"),
           Dur1 = str_extract(.$Comparison, '\\.[:digit:]+? - ') %>% str_remove("\\.") %>% str_remove(" - ") %>% as.numeric(),
           Dur2 = str_extract(.$Comparison, '\\.[:digit:]+?$') %>% str_remove("\\.") %>% as.numeric(),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(G1 == G2 & Dur1 == Dur2) %>%
    rename(Genotype = G1, Stim_Time = Dur1) %>%
    select(Genotype, Stim_Time, Duration_1, Duration_2, Z, P.adj, Sig) %>%
    arrange(Genotype, Stim_Time, Duration_1, Duration_2) %>%
    filter(Genotype == "Het")

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           G1 = str_extract(.$Comparison, '_[:alpha:]+?\\.') %>% str_remove("_") %>% str_remove("\\."),
           G2 = str_extract(.$Comparison, ' - Tsc2_LE_.*?[:punct:]') %>% str_remove(" - Tsc2_LE_") %>% str_remove("\\."),
           Duration_1 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+? - ') %>% str_remove("\\.[:digit:]+ - "),
           Duration_2 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+?$') %>% str_remove("\\.[:digit:]+"),
           Dur1 = str_extract(.$Comparison, '\\.[:digit:]+? - ') %>% str_remove("\\.") %>% str_remove(" - ") %>% as.numeric(),
           Dur2 = str_extract(.$Comparison, '\\.[:digit:]+?$') %>% str_remove("\\.") %>% as.numeric(),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(G1 == G2 & Dur1 == Dur2) %>%
    rename(Genotype = G1, Stim_Time = Dur1) %>%
    select(Genotype, Stim_Time, Duration_1, Duration_2, Z, P.adj, Sig) %>%
    arrange(Genotype, Stim_Time, Duration_1, Duration_2) %>%
    filter(Genotype == "WT")

postHoc$res %>% 
    as_tibble() %>%
    select(-P.unadj) %>%
    mutate(Sig = gtools::stars.pval(P.adj),
           G1 = str_extract(.$Comparison, '_[:alpha:]+?\\.') %>% str_remove("_") %>% str_remove("\\."),
           G2 = str_extract(.$Comparison, ' - Tsc2_LE_.*?[:punct:]') %>% str_remove(" - Tsc2_LE_") %>% str_remove("\\."),
           Duration_1 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+? - ') %>% str_remove("\\.[:digit:]+ - "),
           Duration_2 = str_extract(.$Comparison, '[:alpha:]+\\.[:digit:]+?$') %>% str_remove("\\.[:digit:]+"),
           Dur1 = str_extract(.$Comparison, '\\.[:digit:]+? - ') %>% str_remove("\\.") %>% str_remove(" - ") %>% as.numeric(),
           Dur2 = str_extract(.$Comparison, '\\.[:digit:]+?$') %>% str_remove("\\.") %>% as.numeric(),
           P.adj = round(P.adj, digits = 3)) %>%
    filter(G1 != G2 & Dur1 == Dur2, Duration_1 == Duration_2) %>%
    rename(Stim_Time = Dur1, Rotating = Duration_1) %>%
    select(G1, G2, Stim_Time, Rotating, Z, P.adj, Sig) %>%
    arrange(G1, G2, Stim_Time, Rotating)


Rxn_overall_by_Duration %>%
  filter(!(Intensity %in% c("90"))) %>%
  filter(!(ID %in% partial.data)) %>%
  # filter(!(Phase == "BBN Rotating")) %>%
  mutate(Duration = gsub("Rotating", "Mix", Duration)) %>%
  mutate(Genotype = str_extract(Genotype, "Het|WT")) %>%
  ggplot(aes(x = Intensity, y = Rxn)) +
  # geom_point(aes(group = ID, color = Genotype), alpha = 0.3)+
  # geom_line(aes(group = ID, color = Genotype), alpha = 0.3)+
  stat_summary(aes(color = Genotype, linetype = Duration, group = interaction(Genotype, Duration)),
               fun = mean,
               fun.min = function(x) mean(x) - se(x),
               fun.max = function(x) mean(x) + se(x),
               geom = "errorbar", width = 1, position = position_dodge(0.1)) +
  stat_summary(aes(color = Genotype, shape = Duration, group = interaction(Genotype, Duration)),
               fun = mean,
               geom = "point", position = position_dodge(0.1), size = 3) +
  stat_summary(aes(color = Genotype, linetype = Duration, group = interaction(Genotype, Duration)), fun = mean, geom = "line") +
  scale_color_manual(labels = c("WT" = "Wildtype", "Het" = bquote("Tsc2"^"+/-")),
                 values = c("WT" = "black", "Het" = "deepskyblue")) +
  labs(title = "Tsc2 Eker",
       caption = paste("Data trough:", head(sort(df$Date, decreasing = TRUE))),
       x = "Intensity (dB)",
       y = "Reaction time (ms, mean +/- SE)") +
  scale_x_continuous(breaks = seq(20, 80, by = 10)) +
  facet_wrap(~ `Dur (ms)` , ncol = 1) +
  theme_classic() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = rgb(235, 235, 235, 255, maxColorValue = 255))
  )

```

```{r}
save(df, loaded_files, Data_over_TH, Rxn, Rxn_overall_by_Duration, file = "Tsc2_analysis.Rdata")
```

